build:
    image: "docker:stable"
    services:
        - "docker:dind"
    stage: "build"
    script:
        - "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}"
        - "docker build -t ${CI_REGISTRY_IMAGE}/ubuntu-base:latest dockerfiles/gitlab/ubuntu-base/"
        - "docker tag ${CI_REGISTRY_IMAGE}/ubuntu-base:latest ${CI_REGISTRY_IMAGE}/ubuntu-base:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker push ${CI_REGISTRY_IMAGE}/ubuntu-base:latest"
        - "docker push ${CI_REGISTRY_IMAGE}/ubuntu-base:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker build -t ${CI_REGISTRY_IMAGE}/ubuntu-unmin:latest dockerfiles/gitlab/ubuntu-unmin/"
        - "docker tag ${CI_REGISTRY_IMAGE}/ubuntu-unmin:latest ${CI_REGISTRY_IMAGE}/ubuntu-unmin:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker push ${CI_REGISTRY_IMAGE}/ubuntu-unmin:latest"
        - "docker push ${CI_REGISTRY_IMAGE}/ubuntu-unmin:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker build -t ${CI_REGISTRY_IMAGE}/dev:latest dockerfiles/gitlab/dev/"
        - "docker tag ${CI_REGISTRY_IMAGE}/dev:latest ${CI_REGISTRY_IMAGE}/dev:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker push ${CI_REGISTRY_IMAGE}/dev:latest"
        - "docker push ${CI_REGISTRY_IMAGE}/dev:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker build -t ${CI_REGISTRY_IMAGE}/dev-lang:latest dockerfiles/gitlab/dev-lang/"
        - "docker tag ${CI_REGISTRY_IMAGE}/dev-lang:latest ${CI_REGISTRY_IMAGE}/dev-lang:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker push ${CI_REGISTRY_IMAGE}/dev-lang:latest"
        - "docker push ${CI_REGISTRY_IMAGE}/dev-lang:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker build -t ${CI_REGISTRY_IMAGE}/dev-lang-java:latest dockerfiles/gitlab/dev-lang-java/"
        - "docker tag ${CI_REGISTRY_IMAGE}/dev-lang-java:latest ${CI_REGISTRY_IMAGE}/dev-lang-java:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker push ${CI_REGISTRY_IMAGE}/dev-lang-java:latest"
        - "docker push ${CI_REGISTRY_IMAGE}/dev-lang-java:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker build -t ${CI_REGISTRY_IMAGE}/dev-dl:latest dockerfiles/gitlab/dev-dl/"
        - "docker tag ${CI_REGISTRY_IMAGE}/dev-dl:latest ${CI_REGISTRY_IMAGE}/dev-dl:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker push ${CI_REGISTRY_IMAGE}/dev-dl:latest"
        - "docker push ${CI_REGISTRY_IMAGE}/dev-dl:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker build -t ${CI_REGISTRY_IMAGE}/irssi:latest dockerfiles/gitlab/irssi/"
        - "docker tag ${CI_REGISTRY_IMAGE}/irssi:latest ${CI_REGISTRY_IMAGE}/irssi:1.28-${CI_COMMIT_SHA:0:8}"
        - "docker push ${CI_REGISTRY_IMAGE}/irssi:latest"
        - "docker push ${CI_REGISTRY_IMAGE}/irssi:1.28-${CI_COMMIT_SHA:0:8}"
