name: 'build'

on:
    schedule:
        - cron: "59 1 * * 5"
    push:
        branches:
            - master
    pull_request:
jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
          - name: "Build:checkout"
            uses: actions/checkout@v2
          - name: "Set environment variables"
            run: |
                echo "GITHUB_SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "${GITHUB_ENV}"
                echo "VCS_REF=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "${GITHUB_ENV}"
                echo "BUILD_DATE=$(TZ=Europe/Paris date -Iseconds)" >> "${GITHUB_ENV}"
          - name: 'Login to github container registry'
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
