name: 'build'

on:
    schedule:
        - cron: "59 1 * * 5"
    push:
        branches:
            - master
    pull_request:
jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
          - name: "Build:checkout"
            uses: actions/checkout@v2
          - name: "Set environment variables"
            run: |
                echo "GITHUB_SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "${GITHUB_ENV}"
                echo "VCS_REF=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "${GITHUB_ENV}"
                echo "BUILD_DATE=$(TZ=Europe/Paris date -Iseconds)" >> "${GITHUB_ENV}"
          - name: 'Login to github container registry'
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
          - name: 'Build image ubuntu-sshd ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/ubuntu-sshd/
                file: dockerfiles/ghcr/ubuntu-sshd/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/ubuntu-sshd:latest,ghcr.io/${{ secrets.CR_USER }}/ubuntu-sshd:1.22,ghcr.io/${{ secrets.CR_USER }}/ubuntu-sshd:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/ubuntu-sshd:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/dev/
                file: dockerfiles/ghcr/dev/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/dev:latest,ghcr.io/${{ secrets.CR_USER }}/dev:1.22,ghcr.io/${{ secrets.CR_USER }}/dev:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/dev:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev-lang ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/dev-lang/
                file: dockerfiles/ghcr/dev-lang/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/dev-lang:latest,ghcr.io/${{ secrets.CR_USER }}/dev-lang:1.22,ghcr.io/${{ secrets.CR_USER }}/dev-lang:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/dev-lang:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev-lang-java ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/dev-lang-java/
                file: dockerfiles/ghcr/dev-lang-java/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/dev-lang-java:latest,ghcr.io/${{ secrets.CR_USER }}/dev-lang-java:1.22,ghcr.io/${{ secrets.CR_USER }}/dev-lang-java:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/dev-lang-java:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev-dl ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/dev-dl/
                file: dockerfiles/ghcr/dev-dl/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/dev-dl:latest,ghcr.io/${{ secrets.CR_USER }}/dev-dl:1.22,ghcr.io/${{ secrets.CR_USER }}/dev-dl:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/dev-dl:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image irssi ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/irssi/
                file: dockerfiles/ghcr/irssi/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/irssi:latest,ghcr.io/${{ secrets.CR_USER }}/irssi:1.22,ghcr.io/${{ secrets.CR_USER }}/irssi:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/irssi:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image ubuntu-base ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/ubuntu-base/
                file: dockerfiles/ghcr/ubuntu-base/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/ubuntu-base:latest,ghcr.io/${{ secrets.CR_USER }}/ubuntu-base:1.22,ghcr.io/${{ secrets.CR_USER }}/ubuntu-base:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/ubuntu-base:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image squid ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/squid/
                file: dockerfiles/ghcr/squid/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/squid:latest,ghcr.io/${{ secrets.CR_USER }}/squid:1.22,ghcr.io/${{ secrets.CR_USER }}/squid:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/squid:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image squid-open ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                context: dockerfiles/ghcr/squid-open/
                file: dockerfiles/ghcr/squid-open/Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/${{ secrets.CR_USER }}/squid-open:latest,ghcr.io/${{ secrets.CR_USER }}/squid-open:1.22,ghcr.io/${{ secrets.CR_USER }}/squid-open:1.22-${{ env.GITHUB_SHA_SHORT }},ghcr.io/${{ secrets.CR_USER }}/squid-open:${{ env.GITHUB_SHA_SHORT }}
