name: 'build'

on:
    workflow_dispatch:
    schedule:
        - cron: "58 1 * * 5"
    push:
        branches:
            - master
jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
          - name: "Build:checkout"
            uses: actions/checkout@v3
          - name: "Set environment variables"
            run: |
                export_ga() {
                    for _name in "${@}"
                    do
                        local _key="${_name%%=*}"
                        local _value="${_name#*=}"
                        [ "${_key}" == "${_name}" ] && _value="${!_name}"
                        export $_key="${_value}"
                        echo "${_key}=${_value}" >> "${GITHUB_ENV}"
                    done
                }

                export_ga GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)"
                export_ga VCS_REF="$(echo ${GITHUB_SHA} | cut -c1-8)"
                export_ga BUILD_DATE="$(TZ=Europe/Paris date -Iseconds)"

                export_ga GH_REGISTRY="ghcr.io"
                export_ga GH_USER="${{ github.actor }}"
                export_ga GH_PREFIX="${GH_REGISTRY}/${GH_USER}"
                export_ga DOCKER_HUB_REGISTRY="docker.io"
                export_ga DOCKER_HUB_USER="${{ vars.DOCKER_HUB_USER }}"
                export_ga DOCKER_HUB_PREFIX="${DOCKER_HUB_REGISTRY}/${DOCKER_HUB_USER}"
          - name: "Install cosign"
            uses: "sigstore/cosign-installer@v3.0.5"
            with:
                cosign-release: "v2.0.2"
          # Workaround: https://github.com/docker/build-push-action/issues/461
          - name: "Setup Docker buildx"
            uses: "docker/setup-buildx-action@v2.5.0"
          - name: 'Login to github container registry'
            uses: docker/login-action@v2.1.0
            with:
                registry: "${{ env.GH_REGISTRY }}"
                username: "${{ env.GH_USER }}"
                password: "${{ secrets.GITHUB_TOKEN }}"
          - name: 'Login to docker hub'
            uses: docker/login-action@v2.1.0
            with:
                registry: "${{ env.DOCKER_HUB_REGISTRY }}"
                username: "${{ env.DOCKER_HUB_USER }}"
                password: "${{ secrets.DOCKER_HUB_TOKEN }}"
          - name: 'Build image ubuntu-sshd ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/ubuntu-sshd/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/ubuntu-sshd/Dockerfile
                tags: ${{ env.GH_PREFIX }}/ubuntu-sshd:latest,${{ env.GH_PREFIX }}/ubuntu-sshd:1.27,${{ env.GH_PREFIX }}/ubuntu-sshd:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/ubuntu-sshd:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/ubuntu-sshd:latest,${{ env.DOCKER_HUB_PREFIX }}/ubuntu-sshd:1.27,${{ env.DOCKER_HUB_PREFIX }}/ubuntu-sshd:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/ubuntu-sshd:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/dev/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/dev/Dockerfile
                tags: ${{ env.GH_PREFIX }}/dev:latest,${{ env.GH_PREFIX }}/dev:1.27,${{ env.GH_PREFIX }}/dev:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/dev:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev:latest,${{ env.DOCKER_HUB_PREFIX }}/dev:1.27,${{ env.DOCKER_HUB_PREFIX }}/dev:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev-lang ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/dev-lang/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/dev-lang/Dockerfile
                tags: ${{ env.GH_PREFIX }}/dev-lang:latest,${{ env.GH_PREFIX }}/dev-lang:1.27,${{ env.GH_PREFIX }}/dev-lang:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/dev-lang:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev-lang:latest,${{ env.DOCKER_HUB_PREFIX }}/dev-lang:1.27,${{ env.DOCKER_HUB_PREFIX }}/dev-lang:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev-lang:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev-lang-java ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/dev-lang-java/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/dev-lang-java/Dockerfile
                tags: ${{ env.GH_PREFIX }}/dev-lang-java:latest,${{ env.GH_PREFIX }}/dev-lang-java:1.27,${{ env.GH_PREFIX }}/dev-lang-java:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/dev-lang-java:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev-lang-java:latest,${{ env.DOCKER_HUB_PREFIX }}/dev-lang-java:1.27,${{ env.DOCKER_HUB_PREFIX }}/dev-lang-java:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev-lang-java:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image dev-dl ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/dev-dl/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/dev-dl/Dockerfile
                tags: ${{ env.GH_PREFIX }}/dev-dl:latest,${{ env.GH_PREFIX }}/dev-dl:1.27,${{ env.GH_PREFIX }}/dev-dl:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/dev-dl:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev-dl:latest,${{ env.DOCKER_HUB_PREFIX }}/dev-dl:1.27,${{ env.DOCKER_HUB_PREFIX }}/dev-dl:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/dev-dl:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image irssi ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/irssi/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/irssi/Dockerfile
                tags: ${{ env.GH_PREFIX }}/irssi:latest,${{ env.GH_PREFIX }}/irssi:1.27,${{ env.GH_PREFIX }}/irssi:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/irssi:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/irssi:latest,${{ env.DOCKER_HUB_PREFIX }}/irssi:1.27,${{ env.DOCKER_HUB_PREFIX }}/irssi:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/irssi:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image rtorrent ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/rtorrent/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/rtorrent/Dockerfile
                tags: ${{ env.GH_PREFIX }}/rtorrent:latest,${{ env.GH_PREFIX }}/rtorrent:1.27,${{ env.GH_PREFIX }}/rtorrent:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/rtorrent:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/rtorrent:latest,${{ env.DOCKER_HUB_PREFIX }}/rtorrent:1.27,${{ env.DOCKER_HUB_PREFIX }}/rtorrent:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/rtorrent:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image ubuntu-base ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/ubuntu-base/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/ubuntu-base/Dockerfile
                tags: ${{ env.GH_PREFIX }}/ubuntu-base:latest,${{ env.GH_PREFIX }}/ubuntu-base:1.27,${{ env.GH_PREFIX }}/ubuntu-base:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/ubuntu-base:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/ubuntu-base:latest,${{ env.DOCKER_HUB_PREFIX }}/ubuntu-base:1.27,${{ env.DOCKER_HUB_PREFIX }}/ubuntu-base:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/ubuntu-base:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image squid ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/squid/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/squid/Dockerfile
                tags: ${{ env.GH_PREFIX }}/squid:latest,${{ env.GH_PREFIX }}/squid:1.27,${{ env.GH_PREFIX }}/squid:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/squid:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/squid:latest,${{ env.DOCKER_HUB_PREFIX }}/squid:1.27,${{ env.DOCKER_HUB_PREFIX }}/squid:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/squid:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image squid-open ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/squid-open/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/squid-open/Dockerfile
                tags: ${{ env.GH_PREFIX }}/squid-open:latest,${{ env.GH_PREFIX }}/squid-open:1.27,${{ env.GH_PREFIX }}/squid-open:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/squid-open:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/squid-open:latest,${{ env.DOCKER_HUB_PREFIX }}/squid-open:1.27,${{ env.DOCKER_HUB_PREFIX }}/squid-open:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/squid-open:${{ env.GITHUB_SHA_SHORT }}
          - name: 'Build image gollum ${{ env.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v4.0.0
            with:
                context: dockerfiles/ghcr/gollum/
                build-args: |
                    VCS_REF=${{ env.VCS_REF }}
                    BUILD_DATE=${{ env.BUILD_DATE }}
                file: dockerfiles/ghcr/gollum/Dockerfile
                tags: ${{ env.GH_PREFIX }}/gollum:latest,${{ env.GH_PREFIX }}/gollum:1.27,${{ env.GH_PREFIX }}/gollum:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_PREFIX }}/gollum:${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/gollum:latest,${{ env.DOCKER_HUB_PREFIX }}/gollum:1.27,${{ env.DOCKER_HUB_PREFIX }}/gollum:1.27-${{ env.GITHUB_SHA_SHORT }},${{ env.DOCKER_HUB_PREFIX }}/gollum:${{ env.GITHUB_SHA_SHORT }}
