name: 'build'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
          - name: "Build:checkout"
            uses: actions/checkout@v2
          - name: "Set GITHUB_SHA_SHORT env var"
            id: github_sha_short
            run: echo "::set-output name=GITHUB_SHA_SHORT::$(echo ${GITHUB_SHA} | cut -c1-8)"
          - name: 'Login to github container registry'
            uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
          - name: 'Build image ubuntu-sshd ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/ubuntu-sshd/
                file: dockerfiles/ghcr/ubuntu-sshd/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/ubuntu-sshd:latest
          - name: 'Build image dev ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/dev/
                file: dockerfiles/ghcr/dev/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/dev:latest
          - name: 'Build image dev-lang ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/dev-lang/
                file: dockerfiles/ghcr/dev-lang/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/dev-lang:latest
          - name: 'Build image dev-lang-java ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/dev-lang-java/
                file: dockerfiles/ghcr/dev-lang-java/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/dev-lang-java:latest
          - name: 'Build image dev-dl ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/dev-dl/
                file: dockerfiles/ghcr/dev-dl/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/dev-dl:latest
          - name: 'Build image irssi ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/irssi/
                file: dockerfiles/ghcr/irssi/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/irssi:latest
          - name: 'Build image rtorrent ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/rtorrent/
                file: dockerfiles/ghcr/rtorrent/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/rtorrent:latest
          - name: 'Build image ubuntu-base ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/ubuntu-base/
                file: dockerfiles/ghcr/ubuntu-base/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/ubuntu-base:latest
          - name: 'Build image squid ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/squid/
                file: dockerfiles/ghcr/squid/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/squid:latest
          - name: 'Build image squid-open ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/squid-open/
                file: dockerfiles/ghcr/squid-open/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/squid-open:latest
          - name: 'Build image gollum ${{ steps.github_sha_short.outputs.GITHUB_SHA_SHORT }}'
            uses: docker/build-push-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.CR_USER }}
                password: ${{ secrets.CR_PAT }}
                context: dockerfiles/ghcr/gollum/
                file: dockerfiles/ghcr/gollum/Dockerfile
                push: true
                tags: ghcr.io/${{ secrets.CR_USER }}/gollum:latest
